train:
  #batch_size: 16
  #learning_rate: 0.0001
  epochs: 50
  #weight_decay: 1e-5
  class_weight: 0.7
  device: "cuda:0"  # or "cpu"
  log_frequency: 100  # Log every 100 steps
  save_dir: "checkpoints/trained"
  checkpoint_frequency: 2

data:
  img_size: [512, 512]
  dir: "data/breast_ultrasonic_dataset"
  augmentation:
    flip: True
    rotation: 15  # degrees
  num_classes: 5

features_model:
  architecture: "resnet50"
  train_last_n_layers: 2  # Number of last layers to train
  train_layer4: True      # Train the entire layer4
  train_bn: True          # Train all batch norm layers

seg_model:
  path: "checkpoints/sam2/sam2.1_hiera_base_plus.pt"
  download_file_path: "checkpoints/sam2/download.sh"
  config: "configs/sam2.1/sam2.1_hiera_b+.yaml"  
